const products = [
    {
        id : 0,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/0ed881ed894a425abb06ad86016901b9_9366/five-ten-trailcross-clip-in-mountain-bike-shoes.jpg",
        title : "Bike Shoes",
        description : "Five Ten Trailcross Clip-In Mountain Bike Shoes for men",
        price : 165.00,
        category : "shoes",
        gender : "male",
    },
    {
        id : 1,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/4c463c1f8b924e00bee2ab820d1139b7_9366/superstar-shoes.jpg",
        title : "Superstar Shoes",
        description : "Women's Originals",
        price : 110.00,
        category : "shoes",
        gender : "female",
    },
    {
        id : 2,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/22b74712af7b482da33eae37013e52f9_9366/tour360-22-golf-shoes.jpg",
        title : "Tour360 22 Golf Shoes",
        description : "Men's golf",
        price : 180.00,
        category : "shoes",
        gender : "male",
    },
    {
        id : 3,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/43ca8c61b03d4f73a19bad0800d36c55_9366/nmd_r1-shoes.jpg",
        title : "NMD_R1 Shoes",
        description : "Originals",
        price : 130.00,
        category : "shoes",
        gender : "male",
    },
    {
        id : 4,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/8d95b42e2918465890185b3f9b8cf64f_9366/predator-accuracy-plus-artificial-grass-soccer-cleats.jpg",
        title : "Soccer Cleats",
        description : "Predator Accuracy+ Artificial Grass Soccer Cleats",
        price : 300.00,
        category : "shoes",
        gender : "male",
    },
    {
        id : 5,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/fe5e8bb4457b491c98d7b33a5bcfd668_9366/designed-for-training-workout-tee.jpg",
        title : "workout shirt",
        description : "Designed for Training Workout Tee",
        price : 35.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 6,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/3fc42e6506a5466aa38dafc40076ec44_9366/essentials-fleece-tapered-cuff-big-logo-pants.jpg",
        title : "Sportswear",
        description : "Essentials Fleece Tapered Cuff Big Logo Pants",
        price : 50.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 7,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/403805f44c084fe78d272cec1913dde6_9366/adicolor-contempo-hoodie.jpg",
        title : "Adicolor Contempo Hoodie",
        description : "Men's Originals",
        price : 90.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 8,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/b685fde08c544f35b205a99ba87f4c89_9366/city-break-shorts.jpg",
        title : "City Break Shorts",
        description : "Men's Sportswear",
        price : 55.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 9,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/9202f5fb28e840dabe390faac159a81f_9366/adicolor-woven-firebird-track-pants.jpg",
        title : "Track Pants",
        description : "Adicolor Woven Firebird Track Pants",
        price : 70.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 10,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/575478fca7f54c7c98f1912e42053366_9366/fc-bayern-dna-windbreaker.jpg",
        title : "FC Bayern Windbreaker",
        description : "Men's soccer",
        price : 100.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 11,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/0b44e7e4db2440e0967dafd000eb7de5_9366/adicolor-classics-beckenbauer-track-pants.jpg",
        title : "Track Pants",
        description : "Adicolor Classics Beckenbauer Track Pants",
        price : 70.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 12,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/4fb8ccea250e46e8bd2aafc90093bca7_9366/essentials-fleece-3-stripes-full-zip-hoodie.jpg",
        title : "Gray hoodie",
        description : "Essentials Fleece 3-Stripes Full-Zip Hoodie",
        price : 65.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 13,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/22c6d996c5704db9bd27ac5a01205c22_9366/essentials-big-logo-tee.jpg",
        title : "Tee shirt",
        description : "Essentials Big Logo Tee",
        price : 30.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 14,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/9ea3b1f9dcdb4247861cafce01256aca_9366/designed-for-training-heat.rdy-hiit-training-tank-top.jpg",
        title : "Tank Top",
        description : "Designed for Training HEAT.RDY HIIT Training Tank Top",
        price : 45.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 15,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/0d23596625a944ae828c43da3bcc22e5_9366/simple-goat-tee.jpg",
        title : "Goat shirt",
        description : "Simple Goat Tee",
        price : 35.00,
        category : "clothing",
        gender : "male",
    },
    {
        id : 16,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/e12aaa3603e74bc2a99aafd300da8adc_9366/adicolor-classics-firebird-track-jacket.jpg",
        title : "Track Jacket",
        description : "Adicolor Classics Firebird Track Jacket",
        price : 80.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 17,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/491293add3944b26884fd0ac602c3bb4_9366/allover-mini-crest-logo-sweatpants.jpg",
        title : "Sweatpants",
        description : "Allover Mini Crest Logo Sweatpants",
        price : 70.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 18,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/465fbde72c484513969eafcd002c2348_9366/adicolor-classics-firebird-track-pants.jpg",
        title : "Track Pants",
        description : "Adicolor Classics Firebird Track Pants",
        price : 70.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 19,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/b3909943f95b4537a265afcd002c684f_9366/adicolor-classics-firebird-track-jacket.jpg",
        title : "Track Jacket",
        description : "Adicolor Classics Firebird Track Jacket",
        price : 80.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 20,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/75114cfe61094a9399c987f3619ff007_9366/all-szn-fleece-boyfriend-hoodie.jpg",
        title : "Hoodie",
        description : "ALL SZN Fleece Boyfriend Hoodie",
        price : 60.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 21,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/0a070a4c66af4e7e972a2ed99386bd14_9366/graphics-floral-firebird-track-top.jpg",
        title : "Track Top",
        description : "Graphics Floral Firebird Track Top",
        price : 90.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 22,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/280d5f6ac80944b68f1b6f11c3a3ccd8_9366/city-escape-cargo-pants.jpg",
        title : "Cargo Pants",
        description : "City Escape Cargo Pants",
        price : 85.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 23,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/6b6e7819d79441fb8ed3b89b29ae3452_9366/adicolor-classics-loose-firebird-track-top.jpg",
        title : "Track Top",
        description : "Adicolor Classics Loose Firebird Track Top",
        price : 80.00,
        category : "clothing",
        gender : "female",
    },
    {
        id : 24,
        image : "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/12dbe5a6ed504843a181aefc00fd5563_9366/tiro-23-league-pants-plus-size.jpg",
        title : "League Pants",
        description : "Tiro 23 League Pants (Plus Size)",
        price : 50.00,
        category : "clothing",
        gender : "female",
    },

];

module.exports = products;